spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
  sql:
    init:
      data-locations: classpath:sql/seedData.sql
