spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgrespw

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
